[package]
name = "mmtk"
version = "0.0.1"
authors = [" <>"]

[lib]
name = "mmtk"
crate-type = ["rlib", "dylib", "staticlib"]
doctest = false

[dependencies]
custom_derive = "0.1.7"
enum_derive = "0.1.7"
libc = "0.2"
lazy_static = "1.0"
log = {version = "0.4.1", features = ["max_level_trace", "release_max_level_off"] }
crossbeam-deque = "0.1"
num_cpus = "1.8.0"

[features]
default = ["nogc", "openjdk"]
nogc = []
semispace = []
jikesrvm = []
openjdk = []
