[package]
name = "mmtk"
version = "0.0.1"
authors = [" <>"]

[lib]
name = "mmtk"
crate-type = ["rlib", "dylib", "staticlib"]
doctest = false

[dependencies]
custom_derive = "0.1"
enum_derive = "0.1"
libc = "0.2"
lazy_static = "1.1"
log = {version = "0.4", features = ["max_level_trace", "release_max_level_off"] }
crossbeam-deque = "0.6"
num_cpus = "1.8"
derivative = "1.0.3"

[features]
default = ["nogc", "openjdk"]
nogc = []
semispace = []
jikesrvm = []
openjdk = []
sanity = []
