[package]
name = "mmtk"
version = "0.2.0"
authors = ["The MMTk Developers <>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "MMTk is a framework for the design and implementation of high-performance and portable memory managers."
homepage = "https://www.mmtk.io"
repository = "https://github.com/mmtk/mmtk-core"
readme = "README.md"
categories = ["memory-management"]
keywords = ["gc", "garbage", "collection", "garbage-collection", "allocation"]

[lib]
name = "mmtk"
crate-type = ["rlib"]
doctest = false

[package.metadata.docs.rs]
features = ["marksweep"]

[dependencies]
custom_derive = "0.1"
enum_derive = "0.1"
libc = "0.2"
jemalloc-sys = {version = "0.3.2", features = ["disable_initial_exec_tls"] }
mimalloc-sys = "0.1.6"
hoard-sys = { git = "https://git@github.com/paigereeves/hoard-sys.git", rev = "36989b877962f086267b1d21d5008c9df0fd0984" }
scalloc-sys = { path = "../scalloc-sys" }
tcmalloc-sys = { path = "../tcmalloc-sys" }
lazy_static = "1.1"
log = {version = "0.4", features = ["max_level_trace", "release_max_level_off"] }
crossbeam-deque = "0.6"
num_cpus = "1.8"
enum-map = "0.6.2"
downcast-rs = "1.1.1"
atomic-traits = "0.2.0"
atomic = "0.4.6"
spin = "0.5.2"
env_logger = "0.8.2"

[dev-dependencies]
crossbeam = "0.7.3"
rand = "0.7.3"

[build-dependencies]
cc = "1.0"

[features]
default = []


# plans
nogc = ["immortalspace", "largeobjectspace"]
semispace = ["immortalspace", "largeobjectspace", "copyspace"]
gencopy = ["immortalspace", "largeobjectspace", "copyspace"]
marksweep = ["mallocspace"]

# spaces
base_spaces = []
vm_space = ["base_spaces"]
ro_space = ["base_spaces"]
code_space  = ["base_spaces"]

immortalspace = []
copyspace = []
largeobjectspace = []
lockfreeimmortalspace = []
mallocspace = []

sanity = []
nogc_lock_free = ["nogc", "lockfreeimmortalspace"]
nogc_no_zeroing = ["nogc_lock_free"]

single_worker = []

# malloc implementations used by marksweep
ms_libc = []
ms_mimalloc = []
ms_jemalloc = []
ms_tcmalloc = [] #Does not work
ms_hoard = []
ms_scalloc = [] #Build script does not work

# malloc implementations used as global allocator
ga_libc = []
ga_mimalloc = []
ga_jemalloc = []
ga_hoard = []
ga_scalloc = []
ga_default = []
