name: OpenJDK Performance Baseline

# on:
#   # Manual dispatch
#   workflow_dispatch:
#   # Or on every sunday 1200am UTC
#   schedule:
#     - cron: '0 0 * * SUN'

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - master

jobs:
  openjdk-baseline:
    runs-on: [self-hosted, Linux, freq-scaling-off]
    # Allow 2 days to run (it currently takes slightly more than 1 day to finish)
    timeout-minutes: 2880
    steps:
      - name: Checkout OpenJDK Binding
        uses: actions/checkout@v2
        with:
          repository: mmtk/mmtk-openjdk
          path: mmtk-openjdk
          submodules: true
      # checkout perf-kit
      - name: Checkout Perf Kit
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_ACCESS_TOKEN }}
          repository: mmtk/ci-perf-kit
          ref: "running-ng"
          path: ci-perf-kit
          submodules: true
      # setup
      - name: Setup
        run: |
          ./ci-perf-kit/scripts/history-run-setup.sh
          sed -i 's/^mmtk[[:space:]]=/#ci:mmtk=/g' mmtk-openjdk/mmtk/Cargo.toml
          sed -i 's/^#[[:space:]]mmtk/mmtk/g' mmtk-openjdk/mmtk/Cargo.toml
      # run
      - name: Performance Run
        timeout-minutes: 2880
        run: |
          export RESULT_REPO=mmtk/ci-perf-result
          export RESULT_REPO_BRANCH=test-chopin
          export RESULT_REPO_ACCESS_TOKEN=${{ secrets.CI_ACCESS_TOKEN }}
          export FROM_DATE=2021-09-15
          ./ci-perf-kit/scripts/openjdk-stock.sh ./mmtk-openjdk/repos/openjdk
