name: Stress Test CI

on:
  # push:
  #   branches:
  #     - master
  pull_request:
    branches:
      - master

jobs:
  jikesrvm-stress-test:
    runs-on: [self-hosted, Linux, freq-scaling-on]
    steps:
      - name: Checkout MMTk Core
        uses: actions/checkout@v2
        with:
          path: mmtk-core
      - name: Checkout JikesRVM Binding
        uses: actions/checkout@v2
        with:
          repository: mmtk/mmtk-jikesrvm
          token: ${{ secrets.CI_ACCESS_TOKEN }}
          path: mmtk-jikesrvm
          submodules: true
      # setup
      - name: Overwrite MMTk core in JikesRVM binding
        run: rsync -avLe mmtk-core/* mmtk-jikesrvm/repos/mmtk-core/
      # SemiSpace
      - name: Build SemiSpace
        run: |
          cd mmtk-jikesrvm/repos/jikesrvm
          python scripts/testMMTk.py -g RFastAdaptiveSemiSpace -j /usr/lib/jvm/java-1.8.0-openjdk-amd64 -- --answer-yes --quick --use-third-party-heap=../../ --use-third-party-build-configs=../../jikesrvm/build/configs --use-external-source=../../jikesrvm/rvm/src
      - name: antlr
        run: ./dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -X:gc:stress_factor=1048576 -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar antlr
      - name: bloat
        run: ./dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -X:gc:stress_factor=1048576 -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar bloat
      - name: eclipse
        run: ./dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -X:gc:stress_factor=1048576 -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar eclipse
      - name: fop
        run: ./dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -X:gc:stress_factor=1048576 -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar fop
      - name: hsqldb
        run: ./dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -X:gc:stress_factor=1048576 -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar hsqldb
      - name: jython
        run: ./dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -X:gc:stress_factor=1048576 -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar jython
      - name: luindex
        run: ./dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -X:gc:stress_factor=1048576 -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar luindex
      - name: lusearch
        run: ./dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -X:gc:stress_factor=1048576 -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar lusearch
      - name: pmd
        run: ./dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -X:gc:stress_factor=1048576 -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar pmd
      - name: xalan
        run: ./dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -X:gc:stress_factor=1048576 -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar xalan
