name: Stress Test CI

on:
  # push:
  #   branches:
  #     - master
  pull_request:
    branches:
      - master

jobs:
  jikesrvm-stress-test:
    runs-on: [self-hosted, Linux, freq-scaling-on]
    steps:
      - name: Checkout MMTk Core
        uses: actions/checkout@v2
        with:
          path: mmtk-core
      - name: Checkout JikesRVM Binding
        uses: actions/checkout@v2
        with:
          repository: mmtk/mmtk-jikesrvm
          token: ${{ secrets.CI_ACCESS_TOKEN }}
          path: mmtk-jikesrvm
          submodules: true
      # setup
      - name: Overwrite MMTk core in JikesRVM binding
        run: rsync -avLe mmtk-core/* mmtk-jikesrvm/repos/mmtk-core/
      # SemiSpace
      - name: Build SemiSpace
        run: |
          cd mmtk-jikesrvm/repos/jikesrvm
          RUSTUP_TOOLCHAIN=nightly-2019-08-26 python scripts/testMMTk.py -g RFastAdaptiveSemiSpace -j /usr/lib/jvm/java-1.8.0-openjdk-amd64 --build-only -- --answer-yes --quick --use-third-party-heap=../../ --use-third-party-build-configs=../../jikesrvm/build/configs --use-external-source=../../jikesrvm/rvm/src
      # Run
      - name: antlr
        if: always()
        run: for i in {1..10}; do mmtk-jikesrvm/repos/jikesrvm/dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -Xms75M -Xmx75M -X:gc:stress_factor=4096 -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar antlr; done
      - name: bloat
        if: always()
        run: for i in {1..10}; do mmtk-jikesrvm/repos/jikesrvm/dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -Xms75M -Xmx75M -X:gc:stress_factor=4096 -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar bloat; done
      - name: eclipse
        if: always()
        run: for i in {1..10}; do mmtk-jikesrvm/repos/jikesrvm/dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -Xms150M -Xmx150M -X:gc:stress_factor=4096 -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar eclipse; done
      - name: fop
        if: always()
        run: for i in {1..10}; do mmtk-jikesrvm/repos/jikesrvm/dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -Xms75M -Xmx75M -X:gc:stress_factor=4096 -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar fop; done
      - name: hsqldb
        if: always()
        run: for i in {1..10}; do mmtk-jikesrvm/repos/jikesrvm/dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -Xms200M -Xmx200M -X:gc:stress_factor=4096 -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar hsqldb; done
      - name: jython
        if: always()
        run: for i in {1..10}; do mmtk-jikesrvm/repos/jikesrvm/dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -Xms75M -Xmx75M -X:gc:stress_factor=4096 -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar jython; done
      - name: luindex
        if: always()
        run: for i in {1..10}; do mmtk-jikesrvm/repos/jikesrvm/dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -Xms75M -Xmx75M -X:gc:stress_factor=4096 -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar luindex; done
      - name: lusearch
        if: always()
        run: for i in {1..10}; do mmtk-jikesrvm/repos/jikesrvm/dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -Xms75M -Xmx75M -X:gc:stress_factor=4096 -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar lusearch; done
      - name: pmd
        if: always()
        run: for i in {1..10}; do mmtk-jikesrvm/repos/jikesrvm/dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -Xms75M -Xmx75M -X:gc:stress_factor=4096 -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar pmd; done
      - name: xalan
        if: always()
        run: for i in {1..10}; do mmtk-jikesrvm/repos/jikesrvm/dist/RFastAdaptiveSemiSpace_x86_64-linux/rvm -Xms100M -Xmx100M -X:gc:stress_factor=4096 -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar xalan; done

  openjdk-stress-test:
    runs-on: [self-hosted, Linux, freq-scaling-on]
    steps:
      - name: Checkout MMTk Core
        uses: actions/checkout@v2
        with:
          path: mmtk-core
      - name: Checkout OpenJDK Binding
        uses: actions/checkout@v2
        with:
          repository: mmtk/mmtk-openjdk
          token: ${{ secrets.CI_ACCESS_TOKEN }}
          path: mmtk-openjdk
          submodules: true
      # setup
      - name: Overwrite MMTk core in openjdk binding
        run: cp -r mmtk-core mmtk-openjdk/repos/
      - name: Setup
        run: |
          sed -i 's/^mmtk[[:space:]]=/#ci:mmtk=/g' mmtk-openjdk/mmtk/Cargo.toml
          sed -i 's/^#[[:space:]]mmtk/mmtk/g' mmtk-openjdk/mmtk/Cargo.toml
      # SemiSpace
      - name: Build SemiSpace
        run: |
          cd mmtk-openjdk/repos/openjdk
          export DEBUG_LEVEL=release
          export MMTK_PLAN=semispace
          export RUSTUP_TOOLCHAIN=nightly-2019-08-26
          sh configure --disable-warnings-as-errors --with-debug-level=$DEBUG_LEVEL
          make CONF=linux-x86_64-normal-server-$DEBUG_LEVEL THIRD_PARTY_HEAP=$PWD/../../openjdk
      # Set stress factor
      - name: Set stress factor
        run: echo "::set-env name=MMTK_STRESS_FACTOR::4096"
      # Run
      - name: antlr
        if: always()
        run: for i in {1..10}; do mmtk-jikesrvm/repos/openjdk/build/linux-x86_64-normal-server-release/jdk/bin/java -XX:+UseThirdPartyHeap -server -XX:MetaspaceSize=100M -Xms500M -Xmx500M -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar antlr; done
      - name: fop
        if: always()
        run: for i in {1..10}; do mmtk-jikesrvm/repos/openjdk/build/linux-x86_64-normal-server-release/jdk/bin/java -XX:+UseThirdPartyHeap -server -XX:MetaspaceSize=100M -Xms500M -Xmx500M -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar fop; done
      - name: luindex
        if: always()
        run: for i in {1..10}; do mmtk-jikesrvm/repos/openjdk/build/linux-x86_64-normal-server-release/jdk/bin/java -XX:+UseThirdPartyHeap -server -XX:MetaspaceSize=100M -Xms500M -Xmx500M -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar luindex; done
      - name: pmd
        if: always()
        run: for i in {1..10}; do mmtk-jikesrvm/repos/openjdk/build/linux-x86_64-normal-server-release/jdk/bin/java -XX:+UseThirdPartyHeap -server -XX:MetaspaceSize=100M -Xms500M -Xmx500M -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar pmd; done
      - name: hsqldb
        if: always()
        run: for i in {1..10}; do mmtk-jikesrvm/repos/openjdk/build/linux-x86_64-normal-server-release/jdk/bin/java -XX:+UseThirdPartyHeap -server -XX:MetaspaceSize=100M -Xms500M -Xmx500M -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar hsqldb; done
      - name: eclipse
        if: always()
        run: for i in {1..10}; do mmtk-jikesrvm/repos/openjdk/build/linux-x86_64-normal-server-release/jdk/bin/java -XX:+UseThirdPartyHeap -server -XX:MetaspaceSize=100M -Xms500M -Xmx500M -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar eclipse; done